config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources "weathers", only: %i[index show create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "weathers#index"
end

app/models/application_record.rb
# frozen_string_literal: true

# Default class all other ActiveRecord classes inherit from
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reading.rb
# frozen_string_literal: true

# Persistence class for weather readings.
class Reading < ApplicationRecord; end

# NOTE: as there is no logic in this persistence class, there's nothing to test here,
#   I chose to not write specs for the Reading model as the code should be well
#   tested in the library.

app/models/weather_service.rb
# frozen_string_literal: true

# The WeatherService object wraps the WeatherAPI library to provide easy access
#   to the data, leaving the technicalities of retrieval to the library class
class WeatherService
  include ActiveModel::Model

  CELSIUS_SCALE = "Celsius"
  FAHRENHEIT_SCALE = "Fahrenheit"
  CACHE_TIMEOUT = 30.minutes

  attr_reader :temp_scale,       # Temperature scale to use, "Celsius" or "Fahrenheit"
              :use_caching,      # Flag to determine if we should cache or not
              :using_cache,      # Flag to tell if the value came from cache or hot
              :cache_timeout,    # How long to set the cache timeout
              :address,          # The address to use in the weather API query
              :temperature       # The current temperature

  validates :address, presence: true
  validates :temp_scale, presence: true, inclusion: { in: [CELSIUS_SCALE, FAHRENHEIT_SCALE] }

  def self.current_weather(address, options = {})
    new(options).current_weather(address)
  end

  def initialize(options = {})
    @options = options
    @temp_scale = options.fetch(:temp_scale, FAHRENHEIT_SCALE)
    @use_caching = options.fetch(:use_caching, true)
    @cache_timeout = options.fetch(:cache_timeout, CACHE_TIMEOUT)
  end

  # @param [String] address: The string to pass to query the service
  # @return [WeatherService] This object
  def current_weather(address)
    @address = address
    @temperature = nil
    return self unless valid?

    begin
      if use_caching
        cached_fetch
      else
        fetch_weather
      end
    rescue KeyError => e
      errors.add(:base, e.message)
    rescue WeatherAPI::Error => e
      errors.add(:api, e.message)
    end

    self
  end

  def success?
    @temperature.present? && errors.empty?
  end
  alias success success?

  private

  def cached_fetch
    @using_cache = true
    @temperature =
      Rails.cache.fetch(cache_key, expires_in: cache_timeout) do
        fetch_weather
      end
  end

  def fetch_weather
    @using_cache = false
    @temperature =
      if temp_scale == FAHRENHEIT_SCALE
        current(address).fetch("temp_f")
      elsif temp_scale == CELSIUS_SCALE
        current(address).fetch("temp_c")
      end
  end

  def cache_key
    "weather_service/#{address}/#{temp_scale}"
  end

  def current(address)
    client.current(address:).fetch("current")
  end

  def client
    @client ||= WeatherAPI.new
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/weathers_controller.rb
# frozen_string_literal: true

# Controller handling requests for a tepm reading at an address
class WeathersController < ApplicationController
  # GET weathers
  def index
    @reading = Reading.new
  end

  # GET weater/:id
  def show
    @reading = Reading.find(show_params[:id])
  end

  # POST weathers
  def create
    ws = WeatherService.current_weather(
      create_params[:address],
      { temp_scale: create_params[:temp_scale], use_caching: true }
    )

    reading = Reading.create({
                               address: ws.address,
                               temperature: ws.temperature,
                               temp_scale: ws.temp_scale,
                               service_errors: ws.errors,
                               used_cache: ws.success? ? ws.using_cache : false,
                               request_ip: request.remote_host
                             })
    redirect_to action: :show, id: reading.id
  end

  private

  def create_params
    params.require(:reading).permit(:address, :temp_scale)
  end

  def show_params
    params.permit(:id)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhatsTheTempRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h2>
      <header class="page-header">
        What's the temp?
      </header>
    </h2>

    <%= yield %>
  </body>
</html>

app/views/weathers/_form.html.erb
<%= form_for(:reading, url: weathers_path) do |f| %>
  Location: <%= f.text_field :address %><br />
  Scale: <%= f.radio_button :temp_scale, WeatherService::FAHRENHEIT_SCALE %> &deg;F
  <%= f.radio_button :temp_scale, WeatherService::CELSIUS_SCALE %> &deg;C
  <br />
  <%=
    f.button do
      content_tag(:strong, "Get the temp")
    end
  %>
<% end %>

app/views/weathers/index.html.erb
<h3>Enter an address</h3>
<p>Acceptable addresses include</p>
<ul>
  <li>zip code</li>
  <li>postal code</li>
  <li>city name</li>
  <li>IP address</li>
  <li>"auto:ip" will look up your external IP</li>
</ul>

<div>
  <%= render partial: 'form'  %>
</div>

app/views/weathers/show.html.erb
<% if @reading.service_errors.present? %>
  <ul>
    <% @reading.service_errors.each do |k, msgs| %>
      <li><strong><%= k %>:</strong>
        <ul>
        <% msgs.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </li>
    <% end %>
  </ul
<% else %>
  <h3>The current temp for <%= @reading.address %> is</h3>
  <h4>
    <%= @reading.temperature %>
    &deg;<%= @reading.temp_scale == WeatherService::FAHRENHEIT_SCALE ? 'F' : 'C' %>
    <% if @reading.used_cache %>
      <span class="cached">(from cache)</span>
    <% end %>
  </h4>
<% end  %>

<hr />

<h2>Try again:</h2>

<%= render partial: 'form' %>